final List movies = [
  Movie(
      id: 1,
      name: '2001 A Space Odyssey',
      category: 'Sci-Fi',
      releseYear: 1968,
      rating: 8.2,
      image: 'Movie_Images/2001 A Space Odyssey.jpg'),
  Movie(
      id: 2,
      name: 'Alien',
      category: 'Sci-Fi',
      releseYear: 1979,
      rating: 8.2,
      image: 'Movie_Images/Alien.jpg'),
  Movie(
      id: 3,
      name: 'American Sniper',
      category: 'Action',
      releseYear: 2014,
      rating: 8.2,
      image: 'Movie_Images/American Sniper.jpg'),
  Movie(
      id: 4,
      name: 'Aquman',
      category: 'Action/Sci-Fi',
      releseYear: 2018,
      rating: 8.2,
      image: 'Movie_Images/Aquaman.jpg'),
  Movie(
      id: 5,
      name: 'Avengers Age of Ultron',
      category: 'Action/Sci-Fi',
      releseYear: 2015,
      rating: 8.2,
      image: 'Movie_Images/Avengers Age Of Ultron.jpg'),
  Movie(
      id: 6,
      name: 'Avengers Endgame',
      category: 'Action/Sci-Fi',
      releseYear: 2019,
      rating: 8.2,
      image: 'Movie_Images/Avengers_Endgame.jpg'),
  Movie(
      id: 7,
      name: 'Batman vs Superman Dawn-of Justice',
      category: 'Action/Sci-Fi',
      releseYear: 2016,
      rating: 8.2,
      image: 'Movie_Images/Batman-vs Superman Dawn-of Justice.jpg'),
  Movie(
      id: 8,
      name: 'Blade Runner',
      category: 'Action/Sci-Fi',
      releseYear: 1979,
      rating: 8.2,
      image: 'Movie_Images/Blade Runner.jpg'),
  Movie(
      id: 9,
      name: 'Doctor Strange',
      category: 'Action/Sci-Fi',
      releseYear: 2016,
      rating: 8.2,
      image: 'Movie_Images/Doctor Strange.jpg'),
  Movie(
      id: 10,
      name: 'GodFather',
      category: 'Action',
      releseYear: 1972,
      rating: 8.2,
      image: 'Movie_Images/GodFather.jpg'),
  Movie(
      id: 11,
      name: 'Godzilla the King of Monsters',
      category: 'Action/Sci-Fi',
      releseYear: 2020,
      rating: 8.2,
      image: 'Movie_Images/Godzilla the King of the Monsters.jpg'),
  Movie(
      id: 12,
      name: 'Godzilla vs Kong',
      category: 'Action/Sci-Fi',
      releseYear: 2021,
      rating: 8.2,
      image: 'Movie_Images/Godzilla vs Kong.jpg'),
  Movie(
      id: 13,
      name: 'Inception',
      category: 'Sci-Fi',
      releseYear: 2010,
      rating: 8.2,
      image: 'Movie_Images/Inception.jpg'),
  Movie(
      id: 14,
      name: 'Inception2',
      category: 'Action/Sci-Fi',
      releseYear: 2010,
      rating: 8.2,
      image: 'Movie_Images/Inception2.jpg'),
  Movie(
      id: 15,
      name: 'Ironman',
      category: 'Action/Sci-Fi',
      releseYear: 2008,
      rating: 8.2,
      image: 'Movie_Images/Ironman.jpg'),
  Movie(
      id: 16,
      name: 'John Wick',
      category: 'Action/Sci-Fi',
      releseYear: 2014,
      rating: 8.2,
      image: 'Movie_Images/John Wick.jpg'),
  Movie(
      id: 17,
      name: 'Joker',
      category: 'Action/Sci-Fi',
      releseYear: 2019,
      rating: 8.2,
      image: 'Movie_Images/Joker.jpg'),
  Movie(
      id: 18,
      name: 'Jurassic Park',
      category: 'Action/Sci-Fi',
      releseYear: 1993,
      rating: 8.2,
      image: 'Movie_Images/Jurassic Park.jpg'),
  Movie(
      id: 19,
      name: 'KickAss',
      category: 'Action/Sci-Fi',
      releseYear: 2010,
      rating: 8.2,
      image: 'Movie_Images/Kick Ass.jpg'),
  Movie(
      id: 20,
      name: 'Kurt Cobain',
      category: 'Action/Sci-Fi',
      releseYear: 1967,
      rating: 8.2,
      image: 'Movie_Images/Kurt Cobain.jpg'),
  Movie(
      id: 21,
      name: 'Mad Max Fury Road',
      category: 'Action/Sci-Fi',
      releseYear: 2015,
      rating: 8.2,
      image: 'Movie_Images/Mad Max Fury Road.jpg'),
  Movie(
      id: 22,
      name: 'Mad Max Fury Road',
      category: 'Action/Sci-Fi',
      releseYear: 2015,
      rating: 8.2,
      image: 'Movie_Images/Mad Max Fury Road.jpg'),
  Movie(
      id: 23,
      name: 'Mad Max MachineGun',
      category: 'Action/Sci-Fi',
      releseYear: 1980,
      rating: 8.2,
      image: 'Movie_Images/Mad max MachineGun.jpg'),
  Movie(
      id: 24,
      name: 'Spectr',
      category: 'Action/Sci-Fi',
      releseYear: 2015,
      rating: 8.2,
      image: 'Movie_Images/Spectr.jpg'),
  Movie(
      id: 25,
      name: 'Sucide Squad',
      category: 'Action/Sci-Fi',
      releseYear: 2016,
      rating: 8.2,
      image: 'Movie_Images/Sucide Squad.jpg'),
  Movie(
      id: 26,
      name: 'Taken3',
      category: 'Action/Sci-Fi',
      releseYear: 2012,
      rating: 8.2,
      image: 'Movie_Images/Taken 3.jpg'),
  Movie(
      id: 27,
      name: 'The Lord of the Rings',
      category: 'Action/Sci-Fi',
      releseYear: 2008,
      rating: 8.2,
      image: 'Movie_Images/The Lord of The Rings.jpg'),
  Movie(
      id: 28,
      name: 'Thor Ragnarok',
      category: 'Action/Sci-Fi',
      releseYear: 2018,
      rating: 8.2,
      image: 'Movie_Images/Thor Ragnarok.jpg'),
  Movie(
      id: 29,
      name: 'Warcraft',
      category: 'Action/Sci-Fi',
      releseYear: 2016,
      rating: 8.2,
      image: 'Movie_Images/Warcraft.jpg'),
  Movie(
      id: 30,
      name: 'Wolverine',
      category: 'Action/Sci-Fi',
      releseYear: 2013,
      rating: 8.2,
      image: 'Movie_Images/Wolverine.jpg'),
  Movie(
      id: 31,
      name: 'X-Man Dark Phoneix',
      category: 'Action/Sci-Fi',
      releseYear: 2019,
      rating: 8.2,
      image: 'Movie_Images/X-Man dark Phoenix.jpg'),
];

class Movie {
  int id;
  String name;
  String category;
  int releseYear;
  double rating;
  String image;

  Movie(
      {this.id,
      this.name,
      this.category,
      this.releseYear,
      this.rating,
      this.image});
}
